name: Daily Commit Workflow

on:
  schedule:
    - cron: '30 9 * * *'  # Runs daily at 9:30 AM UTC (adjust as needed)
  workflow_dispatch:      # Allows manual trigger

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Git Config 
        run: |
          git config user.name "AnnanyaPs"
          git config user.email "23f3002003@ds.study.iitm.ac.in"

      - name: Update Daily File
        run: |
          echo "Daily update: $(date -u)" >> daily_updates.txt

      - name: Commit Changes
        run: |
          git add daily_updates.txt
          git commit -m "Daily update - $(date -u)" || echo "No changes to commit"
          git push
